### ISSUE TITLE
NullReferenceException in SelectionMultiple ClearObsoleteItems

### ISSUE THREAD

**Issue by ttustonic** [dotnetprojects/TreeViewEx#1]
Method ClearObsoleteItems in SelectionMultiple throws NullReferenceException when removing an item from the underlying collection, because SelectedItems is null. 
Checking for SelectedItems seems to work:

```
    public void ClearObsoleteItems(IEnumerable<object> items)
    {
            if (treeViewEx.SelectedItems == null)
                return;
            foreach (object itemToUnSelect in items)
            {
                if (treeViewEx.SelectedItems.Contains(itemToUnSelect))
                    treeViewEx.SelectedItems.Remove(itemToUnSelect);
            }
            if (items.Contains(lastShiftRoot))
                lastShiftRoot = null;
    }
```

**Comment by nkast** [comment]
How SelectedItems became null? Did you set it or bind it to null somewhere?
Doesn't this cause NullReferenceException elsewhere?

**Comment by ttustonic** [comment]
It can be null if nothing is selected, like when the treeview is databound to the collection which is modified outside the treeview (for example in the background task, or some command elsewhere on the UI).
I didn't bind it nor did I set it anywhere.
I didn't check, but my test seems to work fine (test includes deleting and adding new item, grouping and filtering).

**Comment by nkast** [comment]
I see. The default value is indeed null. 
https://github.com/tainicom/TreeViewEx/blob/efbcdc4984ebd2ba1fdc336b596ce6e1ba8d4612/TreeViewEx/Controls/TreeViewEx.cs#L73-L78

**Comment by nkast** [comment]
I wasn't able to reproduce. The SelectedItems is initialized first thing in the  TreeViewEx() constructor.
https://github.com/dotnetprojects/TreeViewEx/blob/master/TreeViewEx/Controls/TreeViewEx.cs#L112

**Comment by ttustonic** [comment]
Uh, yes. I had a typo in the XAML. I did bind SelectedItems to my SelectedItem (instead of SelectedItem**s**) object, which indeed was null. 
Sorry for the trouble.
